import { BORDER_RADIUS, COLORS, FONT_SIZES, FONT_WEIGHTS, SPACING } from '@/constants/styles';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  verseDisplayContainer: {
    flex: 1,
    paddingHorizontal: SPACING.xl,
  },
  navigationContainer: {
    marginBottom: SPACING.md,
  },
  versesScrollView: {
    flex: 1,
  },
  verseItem: {
    marginBottom: SPACING.xl,
    width: '100%',
  },
  verseLabel: {
    fontSize: FONT_SIZES.md,
    fontWeight: FONT_WEIGHTS.bold,
    color: COLORS.textSecondary,
    marginBottom: SPACING.sm,
  },
  verseText: {
    fontSize: FONT_SIZES.lg,
    lineHeight: 28,
    color: COLORS.text,
    textAlign: 'justify',
    flexShrink: 1,
  },
  chapterHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SPACING.lg,
    paddingBottom: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  navButton: {
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.sm,
    backgroundColor: COLORS.surface,
    borderRadius: BORDER_RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 40,
  },
  navButtonDisabled: {
    backgroundColor: COLORS.background,
    borderColor: '#e0e0e0',
  },
  chapterTitleContainer: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: SPACING.md,
  },
  chapterTitle: {
    fontSize: FONT_SIZES.xl,
    fontWeight: FONT_WEIGHTS.bold,
    color: COLORS.text,
    flex: 1,
  },
  backToChaptersButton: {
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.sm,
    backgroundColor: COLORS.accent,
    borderRadius: BORDER_RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  verseTextContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    width: '100%',
    flex: 1,
  },
  superscriptContainer: {
    marginHorizontal: 1,
    paddingVertical: 2,
    paddingHorizontal: 2,
    minHeight: 20,
    minWidth: 20,
    backgroundColor: 'rgba(184, 134, 11, 0.1)',
    borderRadius: 3,
    alignSelf: 'flex-start',
  },
  superscriptText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#B8860B',
    textDecorationLine: 'underline',
  },
  anchorContainer: {
    marginHorizontal: 2,
    paddingVertical: 1,
    paddingHorizontal: 3,
    backgroundColor: 'rgba(0, 122, 255, 0.1)',
    borderRadius: 3,
    alignSelf: 'flex-start',
  },
  anchorText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#007AFF',
    textDecorationLine: 'underline',
  },
  chapterFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: SPACING.lg,
    paddingTop: SPACING.lg,
    paddingBottom: SPACING.md,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  footerNavButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.lg,
    backgroundColor: COLORS.surface,
    borderRadius: BORDER_RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    minWidth: 120,
    justifyContent: 'center',
  },
  footerNavButtonDisabled: {
    backgroundColor: COLORS.background,
    borderColor: '#e0e0e0',
  },
  footerNavButtonText: {
    fontSize: FONT_SIZES.md,
    fontWeight: FONT_WEIGHTS.medium,
    color: COLORS.text,
    marginHorizontal: SPACING.sm,
  },
  footerNavButtonTextDisabled: {
    color: '#ccc',
  },
});
